fix symbolic hardware mmio not working
S2E/s2e pull request #77
Opened 2023-03-03 07:30 UTC by ihopenot

The io_read_chk function failed to handle the value returned by tcg_llvm_trace_mmio_access, causing the SymbolicHardware plugin to malfunction.

2023-03-04 19:49 UTC, vitalych commented
thanks, please change the commit message to: `libcpu/softmmu_template: fixed symbolic hardware mmio`.
- We use a prefix for messages to quickly see which modules the commit affects
- `not working` is sort of redundant with `fixed`

2023-03-08 01:59 UTC, ihopenot commented
fixed

2023-03-11 23:58 UTC, vitalych requested changes
This fix breaks the testsuite for some reason. For example, the test basic7-instmon does not work anymore. Please check http://s2e.systems/docs/Testsuite.html on how to run it.

2024-09-22 09:53 UTC, vitalych commented
No activity

2024-09-22 09:53 UTC, closed without merging