Update s2e.asm to fix stack imbalance
S2E/s2e pull request #91
Opened 2024-04-12 08:28 UTC by yype

Hello there, I recently discovered that the i386 asm stub for `S2ESetCpuLogLevel` leads to an unbalanced stack. I figure I should bring it to your attention, although I'm not sure if this function is still actively being used. Thank you.

2024-04-13 18:56 UTC, vitalych commented
That API does not do anything, it's better to remove it from header files as well as from BaseInstructions.cpp.

2024-04-13 18:56 UTC, vitalych requested changes
See comment

2024-04-13 22:57 UTC, yype commented
> That API does not do anything, it's better to remove it from header files as well as from BaseInstructions.cpp.

That makes sense. Removed as suggested.

2024-04-14 09:36 UTC, vitalych approved these changes

2024-04-14 10:09 UTC, merged